import '../models/alphabetsModel.dart';

List<AlphabetsModel> alphabetsList = [
  AlphabetsModel(text: 'A', audio: 'assets/audios/alphabets/A.mp3'),
  AlphabetsModel(text: 'B', audio: 'assets/audios/alphabets/B.mp3'),
  AlphabetsModel(text: 'C', audio: 'assets/audios/alphabets/C.mp3'),
  AlphabetsModel(text: 'D', audio: 'assets/audios/alphabets/D.mp3'),
  AlphabetsModel(text: 'E', audio: 'assets/audios/alphabets/E.mp3'),
  AlphabetsModel(text: 'F', audio: 'assets/audios/alphabets/F.mp3'),
  AlphabetsModel(text: 'G', audio: 'assets/audios/alphabets/G.mp3'),
  AlphabetsModel(text: 'H', audio: 'assets/audios/alphabets/H.mp3'),
  AlphabetsModel(text: 'I', audio: 'assets/audios/alphabets/I.mp3'),
  AlphabetsModel(text: 'J', audio: 'assets/audios/alphabets/J.mp3'),
  AlphabetsModel(text: 'K', audio: 'assets/audios/alphabets/K.mp3'),
  AlphabetsModel(text: 'L', audio: 'assets/audios/alphabets/L.mp3'),
  AlphabetsModel(text: 'M', audio: 'assets/audios/alphabets/M.mp3'),
  AlphabetsModel(text: 'N', audio: 'assets/audios/alphabets/N.mp3'),
  AlphabetsModel(text: 'O', audio: 'assets/audios/alphabets/O.mp3'),
  AlphabetsModel(text: 'P', audio: 'assets/audios/alphabets/P.mp3'),
  AlphabetsModel(text: 'Q', audio: 'assets/audios/alphabets/Q.mp3'),
  AlphabetsModel(text: 'R', audio: 'assets/audios/alphabets/R.mp3'),
  AlphabetsModel(text: 'S', audio: 'assets/audios/alphabets/S.mp3'),
  AlphabetsModel(text: 'T', audio: 'assets/audios/alphabets/T.mp3'),
  AlphabetsModel(text: 'U', audio: 'assets/audios/alphabets/U.mp3'),
  AlphabetsModel(text: 'V', audio: 'assets/audios/alphabets/V.mp3'),
  AlphabetsModel(text: 'W', audio: 'assets/audios/alphabets/W.mp3'),
  AlphabetsModel(text: 'X', audio: 'assets/audios/alphabets/X.mp3'),
  AlphabetsModel(text: 'Y', audio: 'assets/audios/alphabets/Y.mp3'),
  AlphabetsModel(text: 'Z', audio: 'assets/audios/alphabets/Z.mp3'),
];
