name: storylingokids
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  just_audio: ^0.9.38
  google_fonts: ^6.2.1
  speech_to_text: ^6.6.2
  bookfx: ^0.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  fonts:
    - family: CabinSketch
      fonts:
        - asset: assets/fonts/CabinSketch-Bold.ttf
          weight: 700
        - asset: assets/fonts/CabinSketch-Regular.ttf
    - family: AdorshoLipi
      fonts:
        - asset: assets/fonts/AdorshoLipi.ttf
    - family: CharuChandan3D
      fonts:
        - asset: assets/fonts/CharuChandan3D-Regular.ttf
  assets:
    - assets/audios/alphabets/
    - assets/audios/animals/
    - assets/audios/birds/
    - assets/audios/colors/
    - assets/audios/effects/
    - assets/audios/numbers/
    - assets/audios/shapes/
    - assets/images/animals/
    - assets/images/background/
    - assets/images/birds/
    - assets/images/shapes/
    - assets/
    - assets/images/stories/
    - assets/images/stories/ABC/
    - assets/images/stories/count/
    - assets/audios/stories/
    - assets/audios/stories/ABC/
    - assets/audios/stories/count/